-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgv7YsUcbIDBqd5uOq
j3sWtST4Dkts1QJ0PPMPvVS/0NygCgYIKoZIzj0DAQehRANCAARRsGXuVfbqYfzF
WNZnPNDsdqClPv8/bxv0QooKdIuBh5WcFgrraJtnhKeYbjWGc2FJEV7Tmf5MatxO
g23RkCVQ
-----END PRIVATE KEY-----
